language: php

php:
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit
